<?php
/*
 * Social Rewards Tab Setting
 */
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}
if (!class_exists('RSSocialReward')) {

    class RSSocialReward {

        public static function init() {

            add_filter('woocommerce_rs_settings_tabs_array', array(__CLASS__, 'reward_system_tab_setting')); // Register a New Tab in a WooCommerce Reward System Settings        

            add_action('woocommerce_rs_settings_tabs_rewardsystem_socialrewards', array(__CLASS__, 'reward_system_register_admin_settings')); // Call to register the admin settings in the Reward System Submenu with general Settings tab        

            add_action('woocommerce_update_options_rewardsystem_socialrewards', array(__CLASS__, 'reward_system_update_settings')); // call the woocommerce_update_options_{slugname} to update the reward system                               

            add_action('admin_init', array(__CLASS__, 'reward_system_default_settings'));            

            add_action('fp_action_to_reset_settings_rewardsystem_socialrewards', array(__CLASS__, 'rs_function_to_reset_social_reward_tab'));
        }

        /*
         * Function to Define Name of the Tab
         */

        public static function reward_system_tab_setting($setting_tabs) {
            if (!is_array($setting_tabs))
                $setting_tabs = (array) $setting_tabs;
            $setting_tabs['rewardsystem_socialrewards'] = __('Social Reward Points', 'rewardsystem');
            return $setting_tabs;
        }

        /*
         * Function label settings to Member Level Tab
         */

        public static function reward_system_admin_fields() {
            global $woocommerce;            
            return apply_filters('woocommerce_rewardsystem_social_reward_settings', array(
                array(
                    'name' => __('Social Reward Settings', 'rewardsystem'),
                    'type' => 'title',
                    'id' => '_rs_social_reward_setting'
                ),
                array(
                    'name' => __('Facebook Application ID', 'rewardsystem'),
                    'desc' => __('Please Enter Application ID of your Facebook', 'rewardsystem'),
                    'id' => 'rs_facebook_application_id',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_facebook_application_id',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Twitter Profile Name', 'rewardsystem'),
                    'desc' => __('Enter the Profile  Name For Twitter Follow ', 'rewardsystem'),
                    'type' => 'text',
                    'id' => 'rs_global_social_twitter_profile_name',
                    'css' => 'min-width:150px;',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Instagram Profile Name', 'rewardsystem'),
                    'desc' => __('Please Enter Profile Name of your Instagram', 'rewardsystem'),
                    'id' => 'rs_instagram_profile_name',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_instagram_profile_name',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('VK Application ID', 'rewardsystem'),
                    'desc' => __('Please Enter Application ID of your VK', 'rewardsystem'),
                    'id' => 'rs_vk_application_id',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_vk_application_id',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Language Selection for Social Icons', 'rewardsystem'),
                    'id' => 'rs_language_selection_for_button',
                    'std' => '1',
                    'default' => '1',
                    'type' => 'radio',
                    'options' => array(
                        '1' => __('English(US)', 'rewardsystem'),
                        '2' => __('Default Site Language', 'rewardsystem'),
                    ),
                    'newids' => 'rs_language_selection_for_button',
                ),
                array('type' => 'sectionend', 'id' => '_rs_reward_point_facebook_application_settings'),
                array(
                    'name' => __('Social Button Position Settings', 'rewardsystem'),
                    'type' => 'title',
                    'id' => '_rs_reward_point_socialrewards_position_settings'
                ),
                array(
                    'name' => __('Social Buttons display Position in Single Product Page', 'rewardsystem'),
                    'id' => 'rs_global_position_sumo_social_buttons',
                    'css' => 'min-width:150px;',
                    'std' => '5',
                    'default' => '5',
                    'desc' => __('Some theme do not support all the positions. If the position not support then it might result in a JQuery Conflict.', 'rewardsystem'),
                    'newids' => 'rs_global_position_sumo_social_buttons',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Before Single Product', 'rewardsystem'),
                        '2' => __('Before Single Product Summary', 'rewardsystem'),
                        '3' => __('Single Product Summary', 'rewardsystem'),
                        '4' => __('After Single Product', 'rewardsystem'),
                        '5' => __('After Single Product Summary', 'rewardsystem'),
                        '6' => __('After Product Meta End', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Social Buttons Position display type', 'rewardsystem'),
                    'id' => 'rs_social_button_position_troubleshoot',
                    'newids' => 'rs_social_button_position_troubleshoot',
                    'css' => 'min-width:150px;',
                    'std' => 'inline',
                    'default' => 'inline',
                    'type' => 'select',
                    'options' => array(
                        'inline' => __('Inline', 'rewardsystem'),
                        'inline-block' => __('Inline Block', 'rewardsystem'),
                        'inline-flex' => __('Inline Flex', 'rewardsystem'),
                        'inline-table' => __('Inline Table', 'rewardsystem'),
                        'table' => __('Table', 'rewardsystem'),
                        'block' => __('Block', 'rewardsystem'),
                        'flex' => __('Flex', 'rewardsystem'),
                    ),
                    'desc_tip' => true,
                ),
                array('type' => 'sectionend', 'id' => '_rs_reward_point_socialrewards_position_settings'),
                array(
                    'name' => __('Social Button URL Settings', 'rewardsystem'),
                    'type' => 'title',
                    'id' => '_rs_reward_point_socialrewards_url_settings'
                ),
                array(
                    'name' => __('Facebook URL Selection', 'rewardsystem'),
                    'id' => 'rs_global_social_facebook_url',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_facebook_url',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Default', 'rewardsystem'),
                        '2' => __('Custom', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Facebook Custom URL', 'rewardsystem'),
                    'desc' => __('Enter the Custom URL that you wish to enable for Facebook', 'rewardsystem'),
                    'type' => 'text',
                    'id' => 'rs_global_social_facebook_url_custom',
                    'css' => 'min-width:150px;',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Twitter URL Selection', 'rewardsystem'),
                    'id' => 'rs_global_social_twitter_url',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_twitter_url',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Default', 'rewardsystem'),
                        '2' => __('Custom', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Twitter Custom URL', 'rewardsystem'),
                    'desc' => __('Enter the Custom URL that you wish to enable for Twitter', 'rewardsystem'),
                    'type' => 'text',
                    'id' => 'rs_global_social_twitter_url_custom',
                    'css' => 'min-width:150px;',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Google URL Selection', 'rewardsystem'),
                    'id' => 'rs_global_social_google_url',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_google_url',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Default', 'rewardsystem'),
                        '2' => __('Custom', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Google Custom URL', 'rewardsystem'),
                    'desc' => __('Enter the Custom URL that you wish to enable for Google', 'rewardsystem'),
                    'type' => 'text',
                    'id' => 'rs_global_social_google_url_custom',
                    'css' => 'min-width:150px;',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('OK.ru URL Selection', 'rewardsystem'),
                    'id' => 'rs_global_social_ok_url',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_ok_url',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Default', 'rewardsystem'),
                        '2' => __('Custom', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('OK.ru Custom URL', 'rewardsystem'),
                    'desc' => __('Enter the Custom URL that you wish to enable for OK.ru', 'rewardsystem'),
                    'type' => 'text',
                    'id' => 'rs_global_social_ok_url_custom',
                    'css' => 'min-width:150px;',
                    'desc_tip' => true,
                ),                
                array('type' => 'sectionend', 'id' => '_rs_reward_point_socialrewards_url_settings'),                
                array(
                    'name' => __('Social Reward Points Global Settings', 'rewardsystem'),
                    'type' => 'title',
                    'id' => '_rs_global_social_reward_points'
                ),
                array(
                    'name' => __('Enable SUMO Reward Points for Social Promotion', 'rewardsystem'),
                    'desc' => __('This helps to Enable Social Reward Points in Global Level', 'rewardsystem'),
                    'id' => 'rs_global_social_enable_disable_reward',
                    'css' => 'min-width:150px;',
                    'std' => '2',
                    'default' => '2',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_enable_disable_reward',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Enable', 'rewardsystem'),
                        '2' => __('Disable', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Facebook Like Reward Type', 'rewardsystem'),
                    'id' => 'rs_global_social_reward_type_facebook',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_reward_type_facebook',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('By Fixed Reward Points', 'rewardsystem'),
                        '2' => __('By Percentage of Product Price', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Facebook Like Reward Points', 'rewardsystem'),
                    'desc' => __('Please Enter Reward Points for facebook', 'rewardsystem'),
                    'id' => 'rs_global_social_facebook_reward_points',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_facebook_reward_points',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Facebook Like Reward Percent %', 'rewardsystem'),
                    'desc' => __('Please Enter Percentage value of Reward Points', 'rewardsystem'),
                    'id' => 'rs_global_social_facebook_reward_percent',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_facebook_reward_percent',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Facebook Share Reward Type', 'rewardsystem'),
                    'id' => 'rs_global_social_reward_type_facebook_share',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_reward_type_facebook_share',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('By Fixed Reward Points', 'rewardsystem'),
                        '2' => __('By Percentage of Product Price', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Facebook Share Reward Points', 'rewardsystem'),
                    'desc' => __('Please Enter Reward Points for facebook share', 'rewardsystem'),
                    'id' => 'rs_global_social_facebook_share_reward_points',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_facebook_share_reward_points',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Facebook Share Reward Percent %', 'rewardsystem'),
                    'desc' => __('Please Enter Percentage value of Reward Points', 'rewardsystem'),
                    'id' => 'rs_global_social_facebook_share_reward_percent',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_facebook_share_reward_percent',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Twitter Tweet Reward Type', 'rewardsystem'),
                    'id' => 'rs_global_social_reward_type_twitter',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_reward_type_twitter',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('By Fixed Reward Points', 'rewardsystem'),
                        '2' => __('By Percentage of Product Price', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Twitter Tweet Reward Points', 'rewardsystem'),
                    'desc' => __('Please Enter Reward Points for Twitter', 'rewardsystem'),
                    'id' => 'rs_global_social_twitter_reward_points',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_twitter_reward_points',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Twitter Tweet Reward Percent %', 'rewardsystem'),
                    'desc' => __('Please Enter Percentage value of Reward Points', 'rewardsystem'),
                    'id' => 'rs_global_social_twitter_reward_percent',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_twitter_reward_percent',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Twitter Follow Reward Type', 'rewardsystem'),
                    'id' => 'rs_global_social_reward_type_twitter_follow',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_reward_type_twitter_follow',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('By Fixed Reward Points', 'rewardsystem'),
                        '2' => __('By Percentage of Product Price', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Twitter Follow Reward Points', 'rewardsystem'),
                    'desc' => __('Please Enter Reward Points for Twitter Follow ', 'rewardsystem'),
                    'id' => 'rs_global_social_twitter_follow_reward_points',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_twitter_follow_reward_points',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Twitter Follow Reward Percent %', 'rewardsystem'),
                    'desc' => __('Please Enter Percentage value of Reward Points', 'rewardsystem'),
                    'id' => 'rs_global_social_twitter_follow_reward_percent',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_twitter_follow_reward_percent',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Google+1 Reward Type', 'rewardsystem'),
                    'desc' => __('Select Social Reward Type for Google by Points/Percentage', 'rewardsystem'),
                    'id' => 'rs_global_social_reward_type_google',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_reward_type_google',
                    'class' => 'show_if_social_tab_enable',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('By Fixed Reward Points', 'rewardsystem'),
                        '2' => __('By Percentage of Product Price', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Google+1 Reward Points', 'rewardsystem'),
                    'desc' => __('Please Enter Reward Points for Google', 'rewardsystem'),
                    'id' => 'rs_global_social_google_reward_points',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_google_reward_points',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Google+1 Reward Percent %', 'rewardsystem'),
                    'desc' => __('Please Enter Percentage value of Reward Points', 'rewardsystem'),
                    'id' => 'rs_global_social_google_reward_percent',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_google_reward_percent',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('VK.com Like Reward Type', 'rewardsystem'),
                    'desc' => __('Select Social Reward Type for VK by Points/Percentage', 'rewardsystem'),
                    'id' => 'rs_global_social_reward_type_vk',
                    'css' => 'min-width:150px;',
                    'class' => 'show_if_social_tab_enable',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_reward_type_vk',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('By Fixed Reward Points', 'rewardsystem'),
                        '2' => __('By Percentage of Product Price', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('VK.com Like Reward Points', 'rewardsystem'),
                    'desc' => __('Please Enter Reward Points for VK', 'rewardsystem'),
                    'id' => 'rs_global_social_vk_reward_points',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_vk_reward_points',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('VK.com Like Reward Percent %', 'rewardsystem'),
                    'desc' => __('Please Enter Percentage value of Reward Points', 'rewardsystem'),
                    'id' => 'rs_global_social_vk_reward_percent',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_vk_reward_percent',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Instagram Follow Reward Type', 'rewardsystem'),
                    'desc' => __('Select Social Reward Type for Instagram Follow by Points/Percentage', 'rewardsystem'),
                    'id' => 'rs_global_social_reward_type_instagram',
                    'css' => 'min-width:150px;',
                    'class' => 'show_if_social_tab_enable',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_reward_type_instagram',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('By Fixed Reward Points', 'rewardsystem'),
                        '2' => __('By Percentage of Product Price', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Instagram Follow Reward Points', 'rewardsystem'),
                    'desc' => __('Please Enter Reward Points for Instagram', 'rewardsystem'),
                    'id' => 'rs_global_social_instagram_reward_points',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_instagram_reward_points',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Instagram Follow Reward Percent %', 'rewardsystem'),
                    'desc' => __('Please Enter Percentage value of Reward Points', 'rewardsystem'),
                    'id' => 'rs_global_social_instagram_reward_percent',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_instagram_reward_percent',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('OK.ru Share Reward Type', 'rewardsystem'),
                    'id' => 'rs_global_social_reward_type_ok_follow',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_social_reward_type_ok_follow',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('By Fixed Reward Points', 'rewardsystem'),
                        '2' => __('By Percentage of Product Price', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('OK.ru Share Reward Points', 'rewardsystem'),
                    'desc' => __('Please Enter Reward Points for OK.ru share', 'rewardsystem'),
                    'id' => 'rs_global_social_ok_follow_reward_points',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_ok_follow_reward_points',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('OK.ru Share Reward Percent %', 'rewardsystem'),
                    'desc' => __('Please Enter Percentage value of Reward Points', 'rewardsystem'),
                    'id' => 'rs_global_social_ok_follow_reward_percent',
                    'class' => 'show_if_social_tab_enable',
                    'css' => 'min-width:150px;',
                    'std' => '',
                    'default' => '',
                    'type' => 'text',
                    'newids' => 'rs_global_social_ok_follow_reward_percent',
                    'desc_tip' => true,
                ),
                array('type' => 'sectionend', 'id' => '_rs_global_social_reward_points'),
                array('name' => __('Social Buttons display Settings'), 'type' => 'title', 'id' => '_rs_global_social_reward_points_show_hide'),
                array(
                    'name' => __('Facebook Like Button', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_facebook_like_button',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_show_hide_facebook_like_button',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Show', 'rewardsystem'),
                        '2' => __('Hide', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Facebook Share Button', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_facebook_share_button',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_show_hide_facebook_share_button',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Show', 'rewardsystem'),
                        '2' => __('Hide', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Twitter Tweet Button', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_twitter_tweet_button',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_show_hide_twitter_tweet_button',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Show', 'rewardsystem'),
                        '2' => __('Hide', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Twitter Follow Button', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_twitter_follow_tweet_button',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_show_hide_twitter_follow_tweet_button',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Show', 'rewardsystem'),
                        '2' => __('Hide', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Google+1 Button', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_google_plus_button',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_show_hide_google_plus_button',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Show', 'rewardsystem'),
                        '2' => __('Hide', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('VK.com Like Button', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_vk_button',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_show_hide_vk_button',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Show', 'rewardsystem'),
                        '2' => __('Hide', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('Instagram Button', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_instagram_button',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_show_hide_instagram_button',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Show', 'rewardsystem'),
                        '2' => __('Hide', 'rewardsystem'),
                    ),
                ),
                array(
                    'name' => __('OK.ru Button', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_ok_button',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'desc_tip' => true,
                    'newids' => 'rs_global_show_hide_ok_button',
                    'type' => 'select',
                    'options' => array(
                        '1' => __('Show', 'rewardsystem'),
                        '2' => __('Hide', 'rewardsystem'),
                    ),
                ),
                array('type' => 'sectionend', 'id' => '_rs_global_social_reward_points_show_hide'),
                array(
                    'name' => __('Social Message Settings', 'rewardsystem'),
                    'type' => 'title',
                    'id' => '_rs_global_social_message_settings'
                ),
                array(
                    'name' => __('Social ToolTip for Facebook', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_social_tooltip_for_facebook',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'type' => 'select',
                    'options' => array(
                        '1' => 'Show',
                        '2' => 'Hide'
                    ),
                    'newids' => 'rs_global_show_hide_social_tooltip_for_facebook',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('ToolTip Facebook Like Message', 'rewardsystem'),
                    'desc' => __('Enter ToolTip Message for Facebook Like', 'rewardsystem'),
                    'id' => 'rs_social_message_for_facebook',
                    'css' => 'min-width:550px;',
                    'std' => 'Facebook Like will fetch you [facebook_like_reward_points] Reward Points',
                    'default' => 'Facebook Like will fetch you [facebook_like_reward_points] Reward Points',
                    'type' => 'textarea',
                    'newids' => 'rs_social_message_for_facebook',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Social ToolTip for Facebook Share', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_social_tooltip_for_facebook_share',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'type' => 'select',
                    'options' => array(
                        '1' => 'Show',
                        '2' => 'Hide'
                    ),
                    'newids' => 'rs_global_show_hide_social_tooltip_for_facebook_share',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('ToolTip Facebook Share Message', 'rewardsystem'),
                    'desc' => __('Enter ToolTip Message for Facebook Share', 'rewardsystem'),
                    'id' => 'rs_social_message_for_facebook_share',
                    'css' => 'min-width:550px;',
                    'std' => 'Facebook Share will fetch you [facebook_share_reward_points] Reward Points',
                    'default' => 'Facebook Share will fetch you [facebook_share_reward_points] Reward Points',
                    'type' => 'textarea',
                    'newids' => 'rs_social_message_for_facebook_share',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Social ToolTip for Twitter', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_social_tooltip_for_twitter',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'type' => 'select',
                    'options' => array(
                        '1' => 'Show',
                        '2' => 'Hide'
                    ),
                    'newids' => 'rs_global_show_hide_social_tooltip_for_twitter',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('ToolTip Twitter Tweet Message ', 'rewardsystem'),
                    'desc' => __('Enter ToolTip Message for Twitter', 'rewardsystem'),
                    'id' => 'rs_social_message_for_twitter',
                    'css' => 'min-width:550px;',
                    'std' => 'Twitter Tweet will fetch you [twitter_tweet_reward_points] Reward Points',
                    'default' => 'Twitter Tweet will fetch you [twitter_tweet_reward_points] Reward Points',
                    'type' => 'textarea',
                    'newids' => 'rs_social_message_for_twitter',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Social ToolTip for Twitter Follow', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_social_tooltip_for_twitter_follow',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'type' => 'select',
                    'options' => array(
                        '1' => 'Show',
                        '2' => 'Hide'
                    ),
                    'newids' => 'rs_global_show_hide_social_tooltip_for_twitter_follow',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('ToolTip Twitter Follow Message ', 'rewardsystem'),
                    'desc' => __('Enter ToolTip Message for Twitter Follow', 'rewardsystem'),
                    'id' => 'rs_social_message_for_twitter_follow',
                    'css' => 'min-width:550px;',
                    'std' => 'Twitter Follow will fetch you [twitter_follow_reward_points] Reward Points',
                    'default' => 'Twitter Follow will fetch you [twitter_follow_reward_points] Reward Points',
                    'type' => 'textarea',
                    'newids' => 'rs_social_message_for_twitter_follow',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Social ToolTip for Google+1', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_social_tooltip_for_google',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'type' => 'select',
                    'options' => array(
                        '1' => 'Show',
                        '2' => 'Hide'
                    ),
                    'newids' => 'rs_global_show_hide_social_tooltip_for_google',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('ToolTip Google+1 Message ', 'rewardsystem'),
                    'desc' => __('Enter ToolTip Message for Google+ Share', 'rewardsystem'),
                    'id' => 'rs_social_message_for_google_plus',
                    'css' => 'min-width:550px;',
                    'std' => 'Google+ Share will fetch you [google_share_reward_points] Reward Points',
                    'default' => 'Google+ Share will fetch you [google_share_reward_points] Reward Points',
                    'type' => 'textarea',
                    'newids' => 'rs_social_message_for_google_plus',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Social ToolTip for VK.com', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_social_tooltip_for_vk',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'type' => 'select',
                    'options' => array(
                        '1' => 'Show',
                        '2' => 'Hide'
                    ),
                    'newids' => 'rs_global_show_hide_social_tooltip_for_vk',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('ToolTip VK.com Like Message ', 'rewardsystem'),
                    'desc' => __('Enter ToolTip Message for VK.com Like', 'rewardsystem'),
                    'id' => 'rs_social_message_for_vk',
                    'css' => 'min-width:550px;',
                    'std' => 'VK Share will fetch you [vk_reward_points] Reward Points',
                    'default' => 'VK Share will fetch you [vk_reward_points] Reward Points',
                    'type' => 'textarea',
                    'newids' => 'rs_social_message_for_vk',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Social ToolTip for Instagram', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_social_tooltip_for_instagram',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'type' => 'select',
                    'options' => array(
                        '1' => 'Show',
                        '2' => 'Hide'
                    ),
                    'newids' => 'rs_global_show_hide_social_tooltip_for_instagram',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('ToolTip Instagram Message ', 'rewardsystem'),
                    'desc' => __('Enter ToolTip Message for Instagram', 'rewardsystem'),
                    'id' => 'rs_social_message_for_instagram',
                    'css' => 'min-width:550px;',
                    'std' => 'Instagram Follow will fetch you [instagram_reward_points] Reward Points',
                    'default' => 'Instagram Follow will fetch you [instagram_reward_points] Reward Points',
                    'type' => 'textarea',
                    'newids' => 'rs_social_message_for_instagram',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Social ToolTip for OK.ru Share', 'rewardsystem'),
                    'id' => 'rs_global_show_hide_social_tooltip_for_ok_follow',
                    'css' => 'min-width:150px;',
                    'std' => '1',
                    'default' => '1',
                    'type' => 'select',
                    'options' => array(
                        '1' => 'Show',
                        '2' => 'Hide'
                    ),
                    'newids' => 'rs_global_show_hide_social_tooltip_for_ok_follow',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('ToolTip OK.ru Share Message ', 'rewardsystem'),
                    'desc' => __('Enter ToolTip Message for OK.ru Share', 'rewardsystem'),
                    'id' => 'rs_social_message_for_ok_follow',
                    'css' => 'min-width:550px;',
                    'std' => 'OK.ru Share will fetch you [ok_share_reward_points] Reward Points',
                    'default' => 'OK.ru Share will fetch you [ok_share_reward_points] Reward Points',
                    'type' => 'textarea',
                    'newids' => 'rs_social_message_for_ok_follow',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Facebook Like Success Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed upon successful Facebook like', 'rewardsystem'),
                    'id' => 'rs_succcess_message_for_facebook_like',
                    'css' => 'min-width:550px;',
                    'std' => 'Thanks for liking the Product.  [facebook_like_reward_points] Reward Points has been added to your Account.',
                    'default' => 'Thanks for liking the Product.  [facebook_like_reward_points] Reward Points has been added to your Account.',
                    'type' => 'textarea',
                    'newids' => 'rs_succcess_message_for_facebook_like',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Facebook Unlike Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed upon when Facebook unlike', 'rewardsystem'),
                    'id' => 'rs_unsucccess_message_for_facebook_unlike',
                    'css' => 'min-width:550px;',
                    'std' => 'You have already Unliked this product on Facebook.You cannot earn points again',
                    'default' => 'You have already Unliked this product on Facebook.You cannot earn points again',
                    'type' => 'textarea',
                    'newids' => 'rs_unsucccess_message_for_facebook_unlike',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Facebook Share Success Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed upon successful Facebook Share', 'rewardsystem'),
                    'id' => 'rs_succcess_message_for_facebook_share',
                    'css' => 'min-width:550px;',
                    'std' => 'Thanks for Sharing the Product.[facebook_share_reward_points] Reward Points has been added to your Account.',
                    'default' => 'Thanks for Sharing the Product.[facebook_share_reward_points] Reward Points has been added to your Account.',
                    'type' => 'textarea',
                    'newids' => 'rs_succcess_message_for_facebook_share',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Facebook Share UnSuccess Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed upon Unsuccessful Facebook Share', 'rewardsystem'),
                    'id' => 'rs_unsucccess_message_for_facebook_share',
                    'css' => 'min-width:550px;',
                    'std' => 'You already shared this post.You cannot earn points again',
                    'default' => 'You already shared this post.You cannot earn points again',
                    'type' => 'textarea',
                    'newids' => 'rs_unsucccess_message_for_facebook_share',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Google+ Share Success Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed upon successful Google+ Share', 'rewardsystem'),
                    'id' => 'rs_succcess_message_for_google_share',
                    'css' => 'min-width:550px;',
                    'std' => 'Thanks for Sharing the Product on Google+ . [google_share_reward_points] Reward Points has been added to your Account',
                    'default' => 'Thanks for Sharing the Product on Google+ . [google_share_reward_points] Reward Points has been added to your Account',
                    'type' => 'textarea',
                    'newids' => 'rs_succcess_message_for_google_share',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Google+ UnShare Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed upon when unshare Google+', 'rewardsystem'),
                    'id' => 'rs_unsucccess_message_for_google_unshare',
                    'css' => 'min-width:550px;',
                    'std' => 'You have already Unshared this product on Google +.You cannot earn points again',
                    'default' => 'You have already Unshared this product on Google +.You cannot earn points again',
                    'type' => 'textarea',
                    'newids' => 'rs_unsucccess_message_for_google_unshare',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Twitter Tweet Success Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed upon successful Twitter Tweet', 'rewardsystem'),
                    'id' => 'rs_succcess_message_for_twitter_share',
                    'css' => 'min-width:550px;',
                    'std' => 'Thanks for the tweet . [twitter_tweet_reward_points] Reward Points has been added to your Account',
                    'default' => 'Thanks for the tweet . [twitter_tweet_reward_points] Reward Points has been added to your Account',
                    'type' => 'textarea',
                    'newids' => 'rs_succcess_message_for_twitter_share',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Twitter Tweet UnSuccess Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed when tweet deleted in Twitter', 'rewardsystem'),
                    'id' => 'rs_unsucccess_message_for_twitter_unshare',
                    'css' => 'min-width:550px;',
                    'std' => 'You have already Unshared this product on Twitter.You cannot earn points again',
                    'default' => 'You have already Unshared this product on Twitter.You cannot earn points again',
                    'type' => 'textarea',
                    'newids' => 'rs_unsucccess_message_for_twitter_unshare',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Twitter Follow Success Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed upon successful Twitter Follow', 'rewardsystem'),
                    'id' => 'rs_succcess_message_for_twitter_follow',
                    'css' => 'min-width:550px;',
                    'std' => 'Thanks for the Follow . [twitter_follow_reward_points] Reward Points has been added to your Account',
                    'default' => 'Thanks for the Follow . [twitter_follow_reward_points] Reward Points has been added to your Account',
                    'type' => 'textarea',
                    'newids' => 'rs_succcess_message_for_twitter_follow',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Twitter Follow UnSuccess Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed when Follow deleted in Twitter', 'rewardsystem'),
                    'id' => 'rs_unsucccess_message_for_twitter_unfollow',
                    'css' => 'min-width:550px;',
                    'std' => 'You have already follow this Profile on Twitter.You cannot earn points again',
                    'default' => 'You have already follow this Profile on Twitter.You cannot earn points again',
                    'type' => 'textarea',
                    'newids' => 'rs_unsucccess_message_for_twitter_unfollow',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('VK Like Success Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed upon successful VK Like', 'rewardsystem'),
                    'id' => 'rs_succcess_message_for_vk',
                    'css' => 'min-width:550px;',
                    'std' => 'Thanks for the like on VK. [vk_reward_points] Reward Points has been added to your Account',
                    'default' => 'Thanks for the like on VK. [vk_reward_points] Reward Points has been added to your Account',
                    'type' => 'textarea',
                    'newids' => 'rs_succcess_message_for_vk',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('VK Unlike Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed Unlike VK', 'rewardsystem'),
                    'id' => 'rs_unsucccess_message_for_vk',
                    'css' => 'min-width:550px;',
                    'std' => 'You have already Unlike this product on VK.You cannot earn points again',
                    'default' => 'You have already Unlike this product on VK.You cannot earn points again',
                    'type' => 'textarea',
                    'newids' => 'rs_unsucccess_message_for_vk',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Instagram Success Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed upon successful Instagram follow', 'rewardsystem'),
                    'id' => 'rs_succcess_message_for_instagram',
                    'css' => 'min-width:550px;',
                    'std' => 'Thanks for the follow on Instagram. [instagram_reward_points] Reward Points has been added to your Account',
                    'default' => 'Thanks for the follow on Instagram. [instagram_reward_points] Reward Points has been added to your Account',
                    'type' => 'textarea',
                    'newids' => 'rs_succcess_message_for_instagram',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('Instagram Unfollow Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed Unfollow Instagram', 'rewardsystem'),
                    'id' => 'rs_unsucccess_message_for_instagram',
                    'css' => 'min-width:550px;',
                    'std' => 'You have already Follow this Profile on Instagram.You cannot earn points again',
                    'default' => 'You have already Follow this Profile on Instagram.You cannot earn points again',
                    'type' => 'textarea',
                    'newids' => 'rs_unsucccess_message_for_instagram',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('OK.ru Share Success Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed upon successful OK.ru Share', 'rewardsystem'),
                    'id' => 'rs_succcess_message_for_ok_follow',
                    'css' => 'min-width:550px;',
                    'std' => 'Thanks for the Share. [ok_share_reward_points] Reward Points has been added to your Account',
                    'default' => 'Thanks for the Share. [ok_share_reward_points] Reward Points has been added to your Account',
                    'type' => 'textarea',
                    'newids' => 'rs_succcess_message_for_ok_follow',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('OK.ru Share UnSuccess Message', 'rewardsystem'),
                    'desc' => __('Enter the Message that will be displayed when Shared in OK.ru', 'rewardsystem'),
                    'id' => 'rs_unsucccess_message_for_ok_unfollow',
                    'css' => 'min-width:550px;',
                    'std' => 'You have already Shared this Profile on OK.ru.You cannot earn points again',
                    'default' => 'You have already Shared this Profile on OK.ru.You cannot earn points again',
                    'type' => 'textarea',
                    'newids' => 'rs_unsucccess_message_for_ok_unfollow',
                    'desc_tip' => true,
                ),
                array('type' => 'sectionend', 'id' => '_rs_global_social_message_settings'),
                array(
                    'name' => __('Facebook Share Button Label Customization', 'rewardsystem'),
                    'type' => 'title',
                    'id' => '_rs_fbshare_button_customization'
                ),
                array(
                    'name' => __('Facebook Share Button Label', 'rewardsystem'),
                    'type' => 'text',
                    'id' => 'rs_fbshare_button_label',
                    'class' => 'rs_fbshare_button_label',
                    'newids' => 'rs_fbshare_button_label',
                    'std' => 'Share',
                    'default' => 'Share',
                    'desc_tip' => true,
                    'desc' => __('Enter the Name of Facebook Share that will be displayed in button', 'rewardsystem'),
                ),
                array('type' => 'sectionend', 'id' => '_rs_fbshare_button_customization'),
                array(
                    'name' => __('ToolTip Customization', 'rewardsystem'),
                    'type' => 'title',
                    'id' => '_rs_global_social_color_customization'
                ),
                array(
                    'name' => __('ToolTip Background Color', 'rewardsystem'),
                    'desc' => __('Enter ToolTip Background Color', 'rewardsystem'),
                    'id' => 'rs_social_tooltip_bg_color',
                    'css' => 'min-width:150px;',
                    'std' => '000',
                    'default' => '000',
                    'type' => 'text',
                    'class' => 'color',
                    'newids' => 'rs_social_tooltip_bg_color',
                    'desc_tip' => true,
                ),
                array(
                    'name' => __('ToolTip Text Color', 'rewardsystem'),
                    'desc' => __('Enter ToolTip Text Color', 'rewardsystem'),
                    'id' => 'rs_social_tooltip_text_color',
                    'css' => 'min-width:150px;',
                    'std' => 'fff',
                    'default' => 'fff',
                    'type' => 'text',
                    'class' => 'color',
                    'newids' => 'rs_social_tooltip_text_color',
                    'desc_tip' => true,
                ),
                array('type' => 'sectionend', 'id' => '_rs_global_social_color_customization'),
                array(
                    'name' => __('Custom CSS', 'rewardsystem'),
                    'type' => 'title',
                    'id' => '_rs_global_social_troubleshoot'
                ),
                array(
                    'name' => __('Custom CSS', 'rewardsystem'),
                    'desc' => __('Choose your Custom CSS Style for Social Sharing Buttons', 'rewardsystem'),
                    'id' => 'rs_social_custom_css',
                    'css' => 'min-width:350px;min-height:250px;',
                    'std' => '.rs_social_sharing_buttons{};'
                    . '.rs_social_sharing_success_message',
                    'default' => '.rs_social_sharing_buttons{};'
                    . '.rs_social_sharing_success_message',
                    'newids' => 'rs_social_custom_css',
                    'type' => 'textarea',
                    'desc_tip' => true,
                ),
                array('type' => 'sectionend', 'id' => '_rs_global_social_troubleshoot'),
                array(
                    'name' => __('Shortcodes used in Social Reward', 'rewardsystem'),
                    'type' => 'title',
                    'id' => 'rs_shortcodes_in_social_reward',
                ),
                array(
                    'type' => 'title',
                    'desc' => '<b>[facebook_like_reward_points]</b> - To display earning points for facebook like<br><br>'
                    . '<b>[facebook_share_reward_points]</b> - To display earning points for facebook share<br><br>'
                    . '<b>[twitter_tweet_reward_points]</b> - To display earning points for twitter tweet<br><br>'
                    . '<b>[twitter_follow_reward_points]</b> - To display earning points for twitter follow<br><br>'
                    . '<b>[google_share_reward_points]</b> - To display earning points for google share<br><br>'
                    . '<b>[vk_reward_points]</b> - To display earning points for vk like<br><br>'
                    . '<b>[instagram_reward_points]</b> - To display earning points for instagram follow<br><br>'
                    . '<b>[ok_share_reward_points]</b> - To display earning points for ok share',
                ),
                array('type' => 'sectionend', 'id' => 'rs_shortcodes_in_social_reward'),
                array('type' => 'sectionend', 'id' => '_rs_social_reward_setting'),
            ));
        }

        /**
         * Registering Custom Field Admin Settings of SUMO Reward Points in woocommerce admin fields funtion
         */
        public static function reward_system_register_admin_settings() {

            woocommerce_admin_fields(RSSocialReward::reward_system_admin_fields());
        }

        /**
         * Update the Settings on Save Changes may happen in SUMO Reward Points
         */
        public static function reward_system_update_settings() {
            woocommerce_update_options(RSSocialReward::reward_system_admin_fields());
        }

        /**
         * Initialize the Default Settings by looping this function
         */
        public static function reward_system_default_settings() {
            global $woocommerce;
            foreach (RSSocialReward::reward_system_admin_fields() as $setting)
                if (isset($setting['newids']) && isset($setting['std'])) {
                    add_option($setting['newids'], $setting['std']);
                }
        }

        public static function rs_function_to_reset_social_reward_tab() {
            $settings = RSSocialReward::reward_system_admin_fields();
            RSTabManagement::rs_function_to_reset_setting($settings);
        }       

    }

    RSSocialReward::init();
}